  -- PIZZA SALES PROJECT 
  
CREATE DATABASE PIZZAHUT;
USE PIZZAHUT ;

SELECT * FROM PIZZAS;
SELECT * FROM PIZZA_TYPES;
SELECT * FROM ORDERS;
SELECT * FROM ORDER_DETAILS;

--  RETRIEVE THE TOTAL NUMBER OF ORDER PLACED 

SELECT COUNT(ORDER_ID) AS TOTAL_ORDERS FROM ORDERS;

-- CALCULATE THE TOTAL REVENUE GENERATED FROM PIZZA SALES 

SELECT 
ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),3) AS TOTAL_SALES
FROM ORDER_DETAILS JOIN 
PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID;

-- IDENTIFY THE HIGHEST PRICE PIZZA 

SELECT PIZZA_TYPES.NAME , PIZZAS.PRICE
FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
ORDER BY PRICE DESC LIMIT 1 ;


--    INDENTIFY THE MOST COMMON SIZE PIZZA ORDER -- 


SELECT QUANTITY , COUNT(ORDER_DETAILS_ID)
FROM ORDER_DETAILS GROUP BY QUANTITY ;


SELECT PIZZAS.SIZE , COUNT(ORDER_DETAILS.ORDER_DETAILS_ID) AS ORDER_COUNT
FROM PIZZAS JOIN ORDER_DETAILS 
ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID 
GROUP BY SIZE ORDER BY ORDER_COUNT DESC  LIMIT 1;


--  LIST THE TOP MOST ORDERED PIZZA TYPES ALONG WITH THIER QUANTITIES -- 

SELECT PIZZA_TYPES.NAME , SUM(ORDER_DETAILS.QUANTITY) as quantity 
FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY  PIZZA_TYPES.NAME order by quantity desc limit 5  ;


    -- JOIN THR NECESSARY TABLE TO FIND THE TOTAL QUANTITY OF EACH PIZZA CATEGORY ORDER 
    
SELECT PIZZA_TYPES.CATEGORY , SUM(ORDER_DETAILS.QUANTITY) as QUANTITY 
FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
JOIN ORDER_DETAILS
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY  PIZZA_TYPES.CATEGORY order by quantity desc limit 1;

-- DETERMINE THE DISTRIBUTION OF ORDERS BY  HOUR OF THE DAY 


SELECT * FROM ORDERS;

SELECT HOUR(TIME) , COUNT(ORDER_ID) AS ORDER_COUNT FROM ORDERS
GROUP BY HOUR(TIME);

          -- JOIN RELEVENT TABLES TO FIND THE CATEGORY WISE DISTRIBUTION OF PIZZAS 
          
          
SELECT CATEGORY , COUNT(NAME) AS DISTRIBUTION FROM PIZZA_TYPES
GROUP BY CATEGORY  ;

   -- GROUP THE ORDERS BY DATE AND CALCULATE THE AVERAGE NUMBER OF PIZZAS ORDERED PER DAY 
   
   
SELECT ROUND(AVG(QUANTITY) , 0) AS AVERAGE_SALES_PERDAY FROM 

(SELECT ORDERS.DATE , SUM(ORDER_DETAILS.QUANTITY) AS QUANTITY 
FROM ORDERS JOIN ORDER_DETAILS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
GROUP BY DATE) AS DATA_QUANTITY ;


           -- DETERMINE THE TOP 3 MOST PIZZA TYPES BASED ON REVENUE 
           
SELECT PIZZA_TYPES.NAME , 
ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),0) AS REVENUE 
FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
JOIN ORDER_DETAILS 
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID 
GROUP BY PIZZA_TYPES.NAME ORDER BY REVENUE DESC LIMIT 3  ; 


-- CALCULATE THE PERCENTAGE CONTRIBUTION OF EACH PIZZA TYPE TO TOTAL REVENUE 


SELECT PIZZA_TYPES.CATEGORY , 
ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),0) /
(
SELECT 
ROUND(SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE),3) AS TOTAL_SALES
FROM ORDER_DETAILS JOIN 
PIZZAS ON PIZZAS.PIZZA_ID = ORDER_DETAILS.PIZZA_ID
) * 100 AS REVENUE
FROM PIZZA_TYPES JOIN PIZZAS 
ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
JOIN ORDER_DETAILS 
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID 
GROUP BY PIZZA_TYPES.CATEGORY ORDER BY REVENUE DESC ;

-- ANALYZE THE COMULATIVE REVENUE OVER THE TIME 
SELECT DATE , SUM(REVENUE) OVER (ORDER BY DATE ) AS CUM_REVENUE 
FROM
(SELECT ORDERS.DATE ,
SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE 
FROM ORDER_DETAILS JOIN PIZZAS 
ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
JOIN ORDERS
ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID 
GROUP BY ORDERS.DATE) AS SALES ;


